#!/bin/sh

SCRIPT="$0"

while [ -h "$SCRIPT" ] ; do
  ls=`ls -ld "$SCRIPT"`
  # Drop everything prior to ->
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=`dirname "$SCRIPT"`/"$link"
  fi
done

OC_HOME=`dirname "$SCRIPT"`
OC_HOME=`cd "$OC_HOME"; pwd`


if [ "$JAVA_HOME" == "" ]; then
	echo "JAVA_HOME is not defined."
	exit 1
fi

if [ ! -f "$JAVA_HOME/bin/java" ]; then
	echo "java executable doesn't exists."
	exit 1
fi

JAVA_OPTS=" -Dochome=$OC_HOME $JAVA_OPTS"
JAVA_OPTS=" -Xmx128m $JAVA_OPTS"

CLASSPATH=$CLASSPATH:$OC_HOME/lib/*

$JAVA_HOME/bin/java $JAVA_OPTS -cp $CLASSPATH "com.ifountain.opsgenie.client.cli.OpsGenieCommandLine" "$@"
