#!/bin/bash 
#
# marid    Startup script for the marid
#
# chkconfig: 2345 90 10
# pidfile: /var/run/marid.pid

# Source function library
. /etc/rc.d/init.d/functions
. /etc/opsgenie/marid/profile

prog="marid"
marid="${JAVA_HOME:-/usr}/bin/java ${MARID_JVM} -cp ${MARID_CLASSPATH} com.ifountain.opsgenie.client.marid.Bootstrap"
RETVAL=0
PID_FILE=/var/run/${prog}.pid
servicelog=/var/log/opsgenie/marid/service.log

start() {
	echo -n $"Starting $prog: "
        nohup runuser -s /bin/bash -l opsgenie -c "$marid"  >>$servicelog 2>&1 &
 	RETVAL=$?	
	PID=$!
	echo $PID > $PID_FILE
	if [ $RETVAL -eq 0 ]; then 
		touch /var/lock/subsys/$prog
		echo_success
	else
		echo_failure
	fi
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE "$marid"
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

### NOT USED
reload() {
	echo -n $"Reloading $prog: "
	killproc -p $PID_FILE "$marid" -HUP
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	condrestart)
		if [ -f /var/lock/subsys/$prog ]; then
			stop
			start
		fi
		;;
	status)
		status -p $PID_FILE $marid
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|condrestart|status}"
		RETVAL=1
esac

exit $RETVAL
