/*
 * OpsGenie REST API
 * OpsGenie API Description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ifountain.opsgenie.client.swagger.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * AlertReportDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T15:24:56.545+03:00")
public class AlertReportDto {
  @JsonProperty("ackTime")
  private Long ackTime = null;

  @JsonProperty("closeTime")
  private Long closeTime = null;

  @JsonProperty("acknowledgedBy")
  private String acknowledgedBy = null;

  @JsonProperty("closedBy")
  private String closedBy = null;

  public AlertReportDto ackTime(Long ackTime) {
    this.ackTime = ackTime;
    return this;
  }

  /**
   * Get ackTime
   *
   * @return ackTime
   **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAckTime() {
    return ackTime;
  }

  public void setAckTime(Long ackTime) {
    this.ackTime = ackTime;
  }

  public AlertReportDto closeTime(Long closeTime) {
    this.closeTime = closeTime;
    return this;
  }

  /**
   * Get closeTime
   *
   * @return closeTime
   **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCloseTime() {
    return closeTime;
  }

  public void setCloseTime(Long closeTime) {
    this.closeTime = closeTime;
  }

  public AlertReportDto acknowledgedBy(String acknowledgedBy) {
    this.acknowledgedBy = acknowledgedBy;
    return this;
  }

  /**
   * Get acknowledgedBy
   *
   * @return acknowledgedBy
   **/
  @ApiModelProperty(example = "null", value = "")
  public String getAcknowledgedBy() {
    return acknowledgedBy;
  }

  public void setAcknowledgedBy(String acknowledgedBy) {
    this.acknowledgedBy = acknowledgedBy;
  }

  public AlertReportDto closedBy(String closedBy) {
    this.closedBy = closedBy;
    return this;
  }

  /**
   * Get closedBy
   *
   * @return closedBy
   **/
  @ApiModelProperty(example = "null", value = "")
  public String getClosedBy() {
    return closedBy;
  }

  public void setClosedBy(String closedBy) {
    this.closedBy = closedBy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertReportDto alertReportDto = (AlertReportDto) o;
    return ObjectUtils.equals(this.ackTime, alertReportDto.ackTime) &&
            ObjectUtils.equals(this.closeTime, alertReportDto.closeTime) &&
            ObjectUtils.equals(this.acknowledgedBy, alertReportDto.acknowledgedBy) &&
            ObjectUtils.equals(this.closedBy, alertReportDto.closedBy);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(ackTime, closeTime, acknowledgedBy, closedBy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertReportDto {\n");

    sb.append("    ackTime: ").append(toIndentedString(ackTime)).append("\n");
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    acknowledgedBy: ").append(toIndentedString(acknowledgedBy)).append("\n");
    sb.append("    closedBy: ").append(toIndentedString(closedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

