/*
 * OpsGenie REST API
 * OpsGenie API Description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ifountain.opsgenie.client.swagger.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;
import org.joda.time.DateTime;

import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;

/**
 * ListedAlertDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-29T15:24:56.545+03:00")
public class ListedAlertDto {
    @JsonProperty("id")
    private String id = null;

    @JsonProperty("tinyId")
    private String tinyId = null;

    @JsonProperty("alias")
    private String alias = null;

    @JsonProperty("message")
    private String message = null;

    @JsonProperty("status")
    private String status = null;

    @JsonProperty("acknowledged")
    private Boolean acknowledged = null;

    @JsonProperty("isSeen")
    private Boolean isSeen = null;

    @JsonProperty("tags")
    private List<String> tags = new ArrayList<String>();

    @JsonProperty("snoozed")
    private Boolean snoozed = null;

    @JsonProperty("snoozedUntil")
    private DateTime snoozedUntil = null;

    @JsonProperty("count")
    private Integer count = null;

    @JsonProperty("lastReceivedAt")
    private DateTime lastReceivedAt = null;

    @JsonProperty("createdAt")
    private DateTime createdAt = null;

    @JsonProperty("updatedAt")
    private DateTime updatedAt = null;

    @JsonProperty("source")
    private String source = null;

    @JsonProperty("owner")
    private String owner = null;

    @JsonProperty("urgency")
    private String urgency = null;

    @JsonProperty("impact")
    private String impact = null;

    @JsonProperty("priority")
    private String priority = null;

    @JsonProperty("teams")
    private List<ListedAlertDtoTeams> teams = new ArrayList<ListedAlertDtoTeams>();

    @JsonProperty("integration")
    private AlertIntegrationDto integration = null;

    @JsonProperty("report")
    private AlertReportDto report = null;

    public ListedAlertDto id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @NotNull
    @ApiModelProperty(example = "null", required = true, value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ListedAlertDto tinyId(String tinyId) {
        this.tinyId = tinyId;
        return this;
    }

    /**
     * Get tinyId
     *
     * @return tinyId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTinyId() {
        return tinyId;
    }

    public void setTinyId(String tinyId) {
        this.tinyId = tinyId;
    }

    public ListedAlertDto alias(String alias) {
        this.alias = alias;
        return this;
    }

    /**
     * Get alias
     *
     * @return alias
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public ListedAlertDto message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get message
     *
     * @return message
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public ListedAlertDto status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public ListedAlertDto acknowledged(Boolean acknowledged) {
        this.acknowledged = acknowledged;
        return this;
    }

    /**
     * Get acknowledged
     *
     * @return acknowledged
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getAcknowledged() {
        return acknowledged;
    }

    public void setAcknowledged(Boolean acknowledged) {
        this.acknowledged = acknowledged;
    }

    public ListedAlertDto isSeen(Boolean isSeen) {
        this.isSeen = isSeen;
        return this;
    }

    /**
     * Get isSeen
     *
     * @return isSeen
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getIsSeen() {
        return isSeen;
    }

    public void setIsSeen(Boolean isSeen) {
        this.isSeen = isSeen;
    }

    public ListedAlertDto tags(List<String> tags) {
        this.tags = tags;
        return this;
    }

    public ListedAlertDto addTagsItem(String tagsItem) {
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     *
     * @return tags
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public ListedAlertDto snoozed(Boolean snoozed) {
        this.snoozed = snoozed;
        return this;
    }

    /**
     * Get snoozed
     * @return snoozed
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getSnoozed() {
        return snoozed;
    }

    public void setSnoozed(Boolean snoozed) {
        this.snoozed = snoozed;
    }

    public ListedAlertDto snoozedUntil(DateTime snoozedUntil) {
        this.snoozedUntil = snoozedUntil;
        return this;
    }

    /**
     * Get snoozedUntil
     *
     * @return snoozedUntil
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getSnoozedUntil() {
        return snoozedUntil;
    }

    public void setSnoozedUntil(DateTime snoozedUntil) {
        this.snoozedUntil = snoozedUntil;
    }

    public ListedAlertDto count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Get count
     * @return count
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public ListedAlertDto lastReceivedAt(DateTime lastReceivedAt) {
        this.lastReceivedAt = lastReceivedAt;
        return this;
    }

    /**
     * Get lastReceivedAt
     * @return lastReceivedAt
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastReceivedAt() {
        return lastReceivedAt;
    }

    public void setLastReceivedAt(DateTime lastReceivedAt) {
        this.lastReceivedAt = lastReceivedAt;
    }

    public ListedAlertDto createdAt(DateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get createdAt
     * @return createdAt
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(DateTime createdAt) {
        this.createdAt = createdAt;
    }

    public ListedAlertDto updatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get updatedAt
     * @return updatedAt
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public ListedAlertDto source(String source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     * @return source
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public ListedAlertDto owner(String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get owner
     * @return owner
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public ListedAlertDto urgency(String urgency) {
        this.urgency = urgency;
        return this;
    }

    /**
     * Get urgency
     * @return urgency
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getUrgency() {
        return urgency;
    }

    public void setUrgency(String urgency) {
        this.urgency = urgency;
    }

    public ListedAlertDto impact(String impact) {
        this.impact = impact;
        return this;
    }

    /**
     * Get impact
     * @return impact
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getImpact() {
        return impact;
    }

    public void setImpact(String impact) {
        this.impact = impact;
    }

    public ListedAlertDto priority(String priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Get priority
     * @return priority
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public ListedAlertDto teams(List<ListedAlertDtoTeams> teams) {
        this.teams = teams;
        return this;
    }

    public ListedAlertDto addTeamsItem(ListedAlertDtoTeams teamsItem) {
        this.teams.add(teamsItem);
        return this;
    }

    /**
     * Get teams
     * @return teams
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<ListedAlertDtoTeams> getTeams() {
        return teams;
    }

    public void setTeams(List<ListedAlertDtoTeams> teams) {
        this.teams = teams;
    }

    public ListedAlertDto integration(AlertIntegrationDto integration) {
        this.integration = integration;
        return this;
    }

    /**
     * Get integration
     *
     * @return integration
     **/
    @ApiModelProperty(example = "null", value = "")
    public AlertIntegrationDto getIntegration() {
        return integration;
    }

    public void setIntegration(AlertIntegrationDto integration) {
        this.integration = integration;
    }

    public ListedAlertDto report(AlertReportDto report) {
        this.report = report;
        return this;
    }

    /**
     * Get report
     * @return report
     **/
    @ApiModelProperty(example = "null", value = "")
    public AlertReportDto getReport() {
        return report;
    }

    public void setReport(AlertReportDto report) {
        this.report = report;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListedAlertDto listedAlertDto = (ListedAlertDto) o;
        return ObjectUtils.equals(this.id, listedAlertDto.id) &&
                ObjectUtils.equals(this.tinyId, listedAlertDto.tinyId) &&
                ObjectUtils.equals(this.alias, listedAlertDto.alias) &&
                ObjectUtils.equals(this.message, listedAlertDto.message) &&
                ObjectUtils.equals(this.status, listedAlertDto.status) &&
                ObjectUtils.equals(this.acknowledged, listedAlertDto.acknowledged) &&
                ObjectUtils.equals(this.isSeen, listedAlertDto.isSeen) &&
                ObjectUtils.equals(this.tags, listedAlertDto.tags) &&
                ObjectUtils.equals(this.snoozed, listedAlertDto.snoozed) &&
                ObjectUtils.equals(this.snoozedUntil, listedAlertDto.snoozedUntil) &&
                ObjectUtils.equals(this.count, listedAlertDto.count) &&
                ObjectUtils.equals(this.lastReceivedAt, listedAlertDto.lastReceivedAt) &&
                ObjectUtils.equals(this.createdAt, listedAlertDto.createdAt) &&
                ObjectUtils.equals(this.updatedAt, listedAlertDto.updatedAt) &&
                ObjectUtils.equals(this.source, listedAlertDto.source) &&
                ObjectUtils.equals(this.owner, listedAlertDto.owner) &&
                ObjectUtils.equals(this.urgency, listedAlertDto.urgency) &&
                ObjectUtils.equals(this.impact, listedAlertDto.impact) &&
                ObjectUtils.equals(this.priority, listedAlertDto.priority) &&
                ObjectUtils.equals(this.teams, listedAlertDto.teams) &&
                ObjectUtils.equals(this.integration, listedAlertDto.integration) &&
                ObjectUtils.equals(this.report, listedAlertDto.report);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(id, tinyId, alias, message, status, acknowledged, isSeen, tags, snoozed, snoozedUntil, count, lastReceivedAt, createdAt, updatedAt, source, owner, urgency, impact, priority, teams, integration, report);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ListedAlertDto {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    tinyId: ").append(toIndentedString(tinyId)).append("\n");
        sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    acknowledged: ").append(toIndentedString(acknowledged)).append("\n");
        sb.append("    isSeen: ").append(toIndentedString(isSeen)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    snoozed: ").append(toIndentedString(snoozed)).append("\n");
        sb.append("    snoozedUntil: ").append(toIndentedString(snoozedUntil)).append("\n");
        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("    lastReceivedAt: ").append(toIndentedString(lastReceivedAt)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
        sb.append("    urgency: ").append(toIndentedString(urgency)).append("\n");
        sb.append("    impact: ").append(toIndentedString(impact)).append("\n");
        sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
        sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
        sb.append("    integration: ").append(toIndentedString(integration)).append("\n");
        sb.append("    report: ").append(toIndentedString(report)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

